/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class oracle_Oracle */

#ifndef _Included_oracle_Oracle
#define _Included_oracle_Oracle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     oracle_Oracle
 * Method:    initiateSee5withTrees
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_oracle_Oracle_initiateSee5withTrees
  (JNIEnv *, jobject, jstring);

/*
 * Class:     oracle_Oracle
 * Method:    initiateSee5withRules
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_oracle_Oracle_initiateSee5withRules
  (JNIEnv *, jobject, jstring);

/*
 * Class:     oracle_Oracle
 * Method:    getPrediction
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_oracle_Oracle_getPrediction
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
