/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CubistJNI */

#ifndef _Included_CubistJNI
#define _Included_CubistJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CubistJNI
 * Method:    initiateCubist
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_CubistJNI_initiateCubist
  (JNIEnv *, jobject, jstring);

/*
 * Class:     CubistJNI
 * Method:    getPrediction
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_CubistJNI_getPrediction
  (JNIEnv *, jobject, jstring);

/*
 * Class:     CubistJNI
 * Method:    getPredictionAndError
 * Signature: (Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_CubistJNI_getPredictionAndError
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
